server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms?serverTimezone=UTC
    username: root
    password: 1234



  jpa:
    hibernate:
      ddl-auto: update #테이블 생성 / 수정
    properties:
      .hibernate:
        show_sql: true
        format_sql: true

        database-platform=org: org.hibernate.dialect.MySQLDialect


  servlet:
    multipart:
       max-file-size: 200MB #파일 한개당 최대 사이즈
       max-request-size: 200MB #요청당 최대 파일 사이즈
  thymeleaf:
    cache: false
courseVideoLocation : c:/lms/video #영상 업로드 경로
courseImgLocation: c:/lms/img # 썸네일 업로드 경로
uploadPath: file:///C:/lms/ #리소스 업로드 경로

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

