server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms?serverTimezone=UTC
    username: root
    password: Rkdmsdl11~




  jpa:
    hibernate:
      ddl-auto: update #테이블 생성 / 수정
    properties:
      .hibernate:
        show_sql: true
        format_sql: true

        database-platform=org: org.hibernate.dialect.MySQLDialect


  servlet:
    multipart:
       max-file-size: 200MB #파일 한개당 최대 사이즈
       max-request-size: 200MB #요청당 최대 파일 사이즈
  thymeleaf:
    cache: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 497858031245-0i9h7mjm7vjeqcbpj635lu1nk6jtbkon.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          
          naver:
            client-id: pnnFVy7A09sZW6mNdUKl
            client-secret: XdpG7IAYqL
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: 70c4d976b0b45b6e04372cf2a3ebf3aa
            client-secret: 7lg5IE9YBzxoBhJaHe3aQbNiWUmo7bFt
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # "인가 코드 받기" 항목
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token # "토큰 받기" 항목token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me # "사용자 정보 가져오기" 항목

courseVideoLocation : c:/lms/video #영상 업로드 경로
courseImgLocation: c:/lms/img # 썸네일 업로드 경로
uploadPath: file:///C:/lms/ #리소스 업로드 경로

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

